name: ebla
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+42

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animated_theme_switcher: ^2.0.8
  biometric_storage: ^5.0.1
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  connectivity_plus: ^6.1.2
  countup: ^0.1.4
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  file_picker: ^8.3.3
  firebase_analytics: ^10.8.0
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.18
  firebase_messaging: ^14.7.3
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.2.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.8
  flutter_webrtc: ^0.12.7
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^11.0.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.1
  local_auth: ^2.1.7
  lottie: ^2.6.0
  multiple_result: ^5.1.0
  package_info_plus: ^8.1.3
  path_provider: ^2.1.1
  pdf: ^3.11.2
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.3.1
  readmore: ^2.2.0
  retrofit: ^4.0.1
  share_plus: ^10.1.4
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  speech_to_text: ^7.0.0
  syncfusion_flutter_datepicker: ^23.1.40
  url_launcher: ^6.2.0
  webview_flutter: ^4.10.0
  open_file: ^3.3.2
  excel: ^4.0.6
  webview_flutter_plus: ^0.4.15
  haptic_feedback: ^0.5.1+1
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
dependency_overrides:
  intl: ^0.19.0
  webview_flutter_android: 4.3.3
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/webviews/
    - assets/webviews/investor_journey/
    - assets/webviews/about_the_authority/
    - assets/webviews/contact/
    - assets/webviews/media_center/
    - assets/xmap/
    - assets/xmap/assets/
    - assets/silhouette.js
#    - .env
  fonts:
    - family: Lusail
      fonts:
        - asset: assets/fonts/Lusail-Bold.otf
          weight: 700
        - asset: assets/fonts/Lusail-Medium.otf
          weight: 500
        - asset: assets/fonts/Lusail-Regular.otf
          weight: 400
        - asset: assets/fonts/Lusail-Light.otf
          weight: 300
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
